"""Add address fields to user model

Revision ID: f28ffb5eb3ad
Revises: 
Create Date: 2026-03-15 13:36:05.157620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28ffb5eb3ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_column('users', 'pincode')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###

